production:
  twitter:
    api_key:
    api_secret:

development:
  twitter:
    api_key: YUKiLI1sqRgGLaxSAsoCT7MCM
    api_secret: wDddYTjSeUWzmWC9Chh3WpilFtaBKjYTS29SBTyRhC3O2wnwvy

test:
  twitter:
    api_key:
    api_secret:
