default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: sochu_development

test:
  <<: *default
  database: sochu_test

production:
  <<: *default
  database: <%= ENV['SOCHU_DATABASE_NAME'] %>
  username: <%= ENV['SOCHU_DATABASE_USER'] %>
  password: <%= ENV['SOCHU_DATABASE_PASSWORD'] %>
